
services:
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - /data/postgres
    ports:
      - "5432:5432"
    restart: always

  server:
    image: tutbrpglfg/server
    build:
      context: .
      target: server
      dockerfile: Dockerfile
    environment:
      - DOCKER=TRUE
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app

  client:
    image: tutbrpglfg/client
    build:
      context: .
      target: client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - DOCKER=TRUE
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
